server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/menudb_dev
    username: postgres
    password: devpassword
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: DEBUG
