server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver           

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

logging:
  level:
    root: DEBUG
    com.yourpackage.userms: TRACE
