server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: WARN
    com.yourpackage.userms: INFO
